---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cable-config
  labels:
    app: cable-cluster
data:
  config.yaml: |
    # Cable Server Configuration

    # Pprof Debugging
    pprof: false

    # Broker ID for cluster, default is 0 for auto mode
    brokerid: 0

    # Initial size of cluster
    clusterSize: 3

    # gRPC Server Port for API
    grpcPort: 1887

    # HTTP Server Port for API
    httpPort: 1888

    # Peer Port for Cluster Communication
    peerPort: 4567

    # Log Level: debug, info, warn, error
    logLevel: "info"

    # Log Format: text, json
    logFormat: "text"

    # Trace Configuration
    trace:
      enabled: false
      otlpEndpoint: otel-collector:4317
      serviceName: cable

    # Metrics Configuration
    metrics:
      enabled: true
      interval: 10
      otlpEndpoint: http://mimir-gateway/otlp/v1/metrics
      serviceName: cable

    # Kafka Configuration
    kafka:
      enabled: false
      brokers:
        - "kafka-broker-0.kafka-broker:9092"
        - "kafka-broker-1.kafka-broker:9092"
        - "kafka-broker-2.kafka-broker:9092"

    # Redis Configuration
    redis:
      db: 0
      enabled: false
      address: "redis-master:6379"
      password: ""
      userPrefix: "cable-user-channels:"

    # Redis Cluster Configuration
    redisCluster:
      enabled: false
      password: ""
      addresses: 
        - "redis-cluster-0.redis-cluster:6379"
        - "redis-cluster-1.redis-cluster:6379"
        - "redis-cluster-2.redis-cluster:6379"
      userPrefix: "cable-user-channels:"

    # Message Route Configuration
    messageRoute:
      # Example message routes, adjust based on your actual message types
      1: 
        enabled: true
        resendType: "user"
        kafkaTopic: "cable-upstream-user"
      2:
        enabled: true
        resendType: "channel"
        kafkaTopic: "cable-upstream-group"

    # Listeners Configuration
    listeners:
      - network: "ws"
        port: 1881
        queueSize: 1024
        autoStart: true
      - network: "wss"
        port: 1882
        queueSize: 1024
        autoStart: false
        tls:
          certFile: "cert.pem"
          keyFile: "key.pem"
      - network: "tcp"
        port: 1883
        queueSize: 1024
        autoStart: true
      - network: "tls"
        port: 1884
        queueSize: 1024
        autoStart: false
        tls:
          certFile: "cert.pem"
          keyFile: "key.pem"
      - network: "udp"
        port: 1885
        queueSize: 1024
        autoStart: true
      - network: "quic"
        port: 1886
        queueSize: 1024
        autoStart: false
        tls:
          certFile: "cert.pem"
          keyFile: "key.pem"

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cable-cluster
  namespace: default
  labels:
    app: cable-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cable-cluster
  serviceName: cable
  template:
    metadata:
      labels:
        app: cable-cluster
    spec:
      containers:
        - name: cable
          image: sutext/cable:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: cable-config-volume
              mountPath: /config.yaml
              subPath: config.yaml
          livenessProbe:
            httpGet:
              path: /health
              port: 1888
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 1888
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: cable-config-volume
          configMap:
            name: cable-config
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate

---
apiVersion: v1
kind: Service
metadata:
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  type: LoadBalancer
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: ws
      port: 1881
      targetPort: 1881
    - protocol: TCP
      name: wss
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: tls
      port: 1884
      targetPort: 1884
    - protocol: UDP
      name: udp
      port: 1885
      targetPort: 1885
    - protocol: UDP
      name: quic
      port: 1886
      targetPort: 1886
    - protocol: TCP
      name: pprof
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: grpc-api
      port: 1887
      targetPort: 1887
    - protocol: TCP
      name: http-api
      port: 1888
      targetPort: 1888
---
apiVersion: v1
kind: Service
metadata:
  name: cable
  labels:
    app: cable
spec:
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: ws
      port: 1881
      targetPort: 1881
    - protocol: TCP
      name: wss
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: tls
      port: 1884
      targetPort: 1884
    - protocol: UDP
      name: udp
      port: 1885
      targetPort: 1885
    - protocol: UDP
      name: quic
      port: 1886
      targetPort: 1886
    - protocol: TCP
      name: pprof
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: grpc-api
      port: 1887
      targetPort: 1887
    - protocol: TCP
      name: http-api
      port: 1888
      targetPort: 1888
  clusterIP: None
