---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cable-cluster
  namespace: default
  labels:
    app: cable-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cable-cluster
  serviceName: cable-cluster
  template:
    metadata:
      labels:
        app: cable-cluster
    spec:
      containers:
        - name: cable
          image: sutext/cable:latest
          imagePullPolicy: Never
          env:
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: debug
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service

metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  type: LoadBalancer
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: endpoint-tcp
      port: 1883
      targetPort: 1883
    - protocol: UDP
      name: endpoint-udp
      port: 1884
      targetPort: 1884
    - protocol: TCP
      name: endpoint-grpc
      port: 1885
      targetPort: 1885
    - protocol: TCP
      name: pprof
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: inspect
      port: 8888
      targetPort: 8888
