---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: cable-cluster
  namespace: default
  labels:
    app: cable-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cable-cluster
  serviceName: cable-cluster
  template:
    metadata:
      labels:
        app: cable-cluster
    spec:
      containers:
        - name: cable
          image: sutext/cable:latest
          imagePullPolicy: Never
          env:
            - name: DEBUG
              value: "true"
            - name: LOG_LEVEL
              value: debug
          livenessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 3
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
---
apiVersion: v1
kind: Service

metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  type: LoadBalancer
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: ws
      port: 1881
      targetPort: 1881
    - protocol: TCP
      name: wss
      port: 1882
      targetPort: 1882
    - protocol: TCP
      name: tcp
      port: 1883
      targetPort: 1883
    - protocol: TCP
      name: tls
      port: 1884
      targetPort: 1884
    - protocol: UDP
      name: udp
      port: 1885
      targetPort: 1885
    - protocol: UDP
      name: quic
      port: 1886
      targetPort: 1886
    - protocol: TCP
      name: pprof
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: admin
      port: 8888
      targetPort: 8888
