---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cable-cluster
  template:
    metadata:
      labels:
        app: cable-cluster
    spec:
      containers:
        - image: sutext/cable:latest
          imagePullPolicy: Never
          name: cable
          env:
            - name: DEBUG
              value: true
            - name: LOG_LEVEL
              value: debug
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  serviceName: cable-cluster
---
apiVersion: v1
kind: Service

metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  type: LoadBalancer
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: endpoint-tcp
      port: 1883
      targetPort: 1883
    - protocol: UDP
      name: endpoint-udp
      port: 1884
      targetPort: 1884
    - protocol: TCP
      name: pprof
      port: 6060
      targetPort: 6060
    - protocol: TCP
      name: inspect
      port: 8888
      targetPort: 8888
