---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cable-cluster
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: cable-cluster
    spec:
      imagePullSecrets:
        - name: pull-image
      containers:
        - image: sutext/cable:latest
          imagePullPolicy: Never
          name: cable
---
apiVersion: v1
kind: Service

metadata:
  namespace: default
  name: cable-cluster
  labels:
    app: cable-cluster
spec:
  type: LoadBalancer
  selector:
    app: cable-cluster
  ports:
    - protocol: TCP
      name: endpoint-tcp
      port: 1883
      targetPort: 1883
    - protocol: UDP
      name: endpoint-udp
      port: 1884
      targetPort: 1884
    - protocol: TCP
      name: inspect
      port: 8888
      targetPort: 8888
